contactmanager/urls.py
from django.urls import path
from contactmanager.page_views.home import HomeView
from contactmanager.page_views.create_profile import CreateProfileView
from contactmanager import views

urlpatterns= [
    path("", HomeView.as_view() , name="home"),
    path("profile", CreateProfileView.as_view(), name="profile")
]

contactproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("contactmanager.urls"))
]
print(settings.DEBUG)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
else:
    urlpatterns += staticfiles_urlpatterns()

contactmanager/models.py
from django.db import models
from django.conf import settings

class Contact(models.Model):
    name = models.CharField(max_length=50, null=False)
    email = models.CharField(max_length=100, null=True)
    mobile = models.CharField(max_length=10, null=False)
    fax = models.CharField(max_length=20, null=True)
    image = models.ImageField(upload_to='images/', blank=True, null=True)
    
    def __str__(self):
        """Return the string representation """
        return f"""Name={self.name}\n
                Email={self.email}\n
                Mobile={self.mobile}\n
                Fax={self.fax}"""

    # save(self, *args, **kwargs):
    #     if(settings.DEBUG):
    #         storage_helper = StorageHelper(settings.STORAGE_CONNECTION_STRING)
    #         storage_helper.create_container(settings.STORAGE_CONTAINER)
    #         storage_helper.upload_blob(self.image)
    #     super(Contact,self).save(*args, **kwargs)

contactmanager/forms.py
from django import forms
from contactmanager.models import Contact


class ContactCreateForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ('name', 'email', 'mobile', 'fax', 'image')
        

contactmanager/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.shortcuts import render, redirect
# from contactmanager.forms import ContactForm
# from contactmanager.models import Contact

# Create your views here.
# def home(request):    
#     model = Contact.objects.all()
#     return render(request, "contactmanager/home.html",{
#         contacts:model
#     } )

# def user_profile(request):
#     if(request.method=='GET'):
#         form = ContactForm()
#     else:
#         form = ContactForm(request.POST, request.FILES)
#         if(form.is_valid()):
#             form.save()
#             return redirect('home')
    
#     return render(request, "contactmanager/profile.html",{ 'form': form})

contactmanager/templates/contactmanager/home.html
{% extends "contactmanager/layout.html" %}

{% block title %}
Contact Manager Application
{% endblock %}

{% block content %}
<h2 class="text-center">User List</h2>
<div class="row">
    {% for contact in object_list %}
    <div class="col-md-4 card">
        <div class="row">
            <div class="col-sm-4 card">
                <div>
                    <img class="card-img-top embed-responsive-item card-imgx" src="{{MEDIA_URL}}{{contact.image}}" alt="{{ contact.name}}" />
                </div>
            </div>
            <div class="col-sm-8">
                <table class="table table-sm">
                    <tr>
                        <td class="small">Name</td>
                        <td class="small">{{contact.name}}</td>
                    </tr>
                    <tr>
                        <td class="small">Email</td>
                        <td class="small">{{contact.email}}</td>
                    </tr>
                    <tr>
                        <td class="small">Mobile</td>
                        <td class="small">{{contact.mobile}}</td>
                    </tr>
                    <tr>
                        <td class="small">Fax</td>
                        <td class="small">{{contact.fax}}</td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

contactmanager/templates/contactmanager/layout.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <title>{% block title %}{% endblock %}</title>

    {# Load the tag library #}
    {% load bootstrap4 %}

    {# Load CSS and JavaScript #}
    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}

    {% load static %}    
    <link rel="stylesheet" type="text/css" href="{% static 'contactmanager/site.css' %}" />
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="{% url 'home' %}">Contacts Manager</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'home' %}">Home</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'profile' %}">Profile</a>
                </li>
            </ul>
        </div>
    </nav>
    <div class="container">
        {% block content %}
        {% endblock %}
        <hr />
    </div>
</body>

</html>

contactmanager/templates/contactmanager/profile.html
{% extends 'contactmanager/layout.html' %}

{% block content %}
<div class="row">
    <div class="col-md-4 mx-auto">
        <h3>Create contact profile</h3>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            
            <div class="form-group">
                <label for="id_name">Name:</label>
                <input type="text" name="name" class="form-control" maxlength="50" required id="id_name">
            </div>
            <div class="form-group">
                <label for="id_email">Email:</label>
                <input type="email" name="email" class="form-control" maxlength="100" required id="id_email">
            </div>
            <div class="form-group">
                <label for="id_mobile">Mobile:</label>
                <input type="text" name="mobile" class="form-control" maxlength="10" required id="id_mobile">
            </div>
            <div class="form-group">
                <label for="id_fax">Fax:</label>
                <input type="text" name="fax" class="form-control" maxlength="20" required id="id_fax">
            </div>
            <div class="form-group">
                <label for="id_image">Image:</label>
                <input type="file" name="image" class="form-control" accept="image/*" id="id_image">
            </div>
            <button type="submit" class="btn btn-primary">Save</button>
        </form>

        <p><a href="{% url 'home' %}">Return to home</a></p>
    </div>
</div>

{% endblock %}